# Generated by Django 4.0.4 on 2022-05-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='create_content',
            field=models.TextField(null=True),
        ),
    ]
