# Generated by Django 4.0.4 on 2022-05-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_alter_write_create_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='create_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
