# Generated by Django 4.0.4 on 2022-05-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0008_alter_write_create_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='write',
            name='create_content',
            field=models.CharField(max_length=10000),
        ),
    ]
